### ISSUE TITLE
Pay per symbols

### ISSUE THREAD

**Issue by gooddaytoday** [TheCrowned/Post-Pay-Counter#11]
Hello!

In Russia we are paying per symbols, not per words. I think, that you will get more clients from my coutry, when introduce this feature. Surely, I'll be the first "Pro version" customer.

**Comment by TheCrowned** [comment]
Hi there, 
Can you provide some examples/details? I don't even exactly know how your language/alphabet works, so I'd really appreciate some information :)

**Comment by gooddaytoday** [comment]
Do you mean that charset influence on char/symbol counting? If it is important, I think supporting only utf-8 will be enough. Our alphabet is symilar with english: it consists of symbols, but 33 (https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9_%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82). 
If you face with some problem with charset or smth within it, I'll help to code (php/js) here.

**Comment by TheCrowned** [comment]
I mean, why do you pay for characters? Is it your own payment scheme or do characters have a different value in russian than in latin languages.

For example, нынешнем should mean _current_. Why wouldn't you pay as a word, but as a list of characters? 

(Also, I'm assuming that you would not pay spaces and punctuation, right?)

**Comment by gooddaytoday** [comment]
Because counting by characters is more accurate than counting by words. Words could be longer or shorter. Of course, assuming big volumes, it'll be more ecual payment for this two different counting systems (Am I right?). 
But.. 
It is not only my payment scheme. It is a standart for all Russian market.

**Comment by gooddaytoday** [comment]
Surely, If you don't want to add such feature in favour of plugin simplicity, you must not to do this.

**Comment by TheCrowned** [comment]
Okay, that's enough for me, I guess there's room for an addon :)

**Comment by gooddaytoday** [comment]
Ok. If you will have some problems with russian characters, I'll help to code.  kiselevgeorgy@gmail.com

**Comment by TheCrowned** [comment]
Thanks! It's gonna be great to have a beta tester :)

**Comment by TheCrowned** [comment]
The addon is out! :)
http://postpaycounter.com/pay-per-character/

Let me know if it works!

**Comment by gooddaytoday** [comment]
Ok, thak you very much! I'll buy and try it later in the evening.

**Comment by gooddaytoday** [comment]
@TheCrowned Hey! Sorry for my late, I was very busy some days. Today I just bought PRO version and 2 addons with this post pay character. But in e-mail with download links to plugins link to post pay character is broken. (Bought as George Kiselev, kiselevgeorgy@gmail.com)

**Comment by TheCrowned** [comment]
Hi George, 
thanks for reporting and sorry for the hiccup, I've just fixed the issue. You can use the download link in the email you already have :)

**Comment by gooddaytoday** [comment]
There is a problem with Russian symbols: they are counts with x2 multiplier. You can solve it by replacing  "str_len" with "mb_stelen" function. I've checked, it works.

Note: issue http://postpaycounter.com/forums2/topic/cannot-revoke-analytics/#post-51775 still exists, revoke analytics don't works in sub-site

**Comment by TheCrowned** [comment]
Okay thanks, will change that in the next release :)
